let upgrades = [
    upgrade = {
        name: "Adrenaline Rush",
        description: "Move faster, but you're a bigger target.",
        coins: 1,
        speed: 1.2,
        damage: 1,
        hp: 0.9,
        regen: 1,
        accuracy: 1,
        bpm: 1
    },
    upgrade = {
        name: "Hollow Point",
        description: "Bullets hit harder.",
        coins: 1,
        speed: 1,
        damage: 1.3,
        hp: 1,
        regen: 1,
        accuracy: 1,
        bpm: 1
    },
    upgrade = {
        name: "Field Medic",
        description: "Recover health faster between fights.",
        coins: 1,
        speed: 1,
        damage: 1,
        hp: 1,
        regen: 1.5,
        accuracy: 1,
        bpm: 1
    },
    upgrade = {
        name: "Trigger Happy",
        description: "Fire faster, but less accurately.",
        coins: 1,
        speed: 1,
        damage: 1,
        hp: 1,
        regen: 1,
        accuracy: 0.85,
        bpm: 1.3
    },
    upgrade = {
        name: "Iron Skin",
        description: "Take more hits before going down.",
        coins: 1,
        speed: 1,
        damage: 1,
        hp: 1.4,
        regen: 1,
        accuracy: 1,
        bpm: 1
    },
    upgrade = {
        name: "Scavenger",
        description: "Enemies drop more coins.",
        coins: 1.5,
        speed: 1,
        damage: 1,
        hp: 1,
        regen: 1,
        accuracy: 1,
        bpm: 1
    },
    upgrade = {
        name: "Sniper's Breath",
        description: "Pinpoint accuracy, slower fire rate.",
        coins: 1,
        speed: 1,
        damage: 1.2,
        hp: 1,
        regen: 1,
        accuracy: 1.4,
        bpm: 0.8
    },
    upgrade = {
        name: "Berserker",
        description: "Everything is faster. Everything.",
        coins: 1,
        speed: 1.3,
        damage: 1.2,
        hp: 0.85,
        regen: 1,
        accuracy: 0.9,
        bpm: 1.3
    },
    upgrade = {
        name: "Turtle Shell",
        description: "Much tankier, but slow as a turtle.",
        coins: 1,
        speed: 0.75,
        damage: 1,
        hp: 1.8,
        regen: 1.3,
        accuracy: 1,
        bpm: 1
    },
    upgrade = {
        name: "Blood Money",
        description: "Risk your health for more coins.",
        coins: 1.8,
        speed: 1,
        damage: 1,
        hp: 0.8,
        regen: 0.8,
        accuracy: 1,
        bpm: 1
    },
    upgrade = {
        name: "Glass Cannon",
        description: "Massive damage, but one hit and you're done.",
        coins: 1,
        speed: 1,
        damage: 1.8,
        hp: 0.5,
        regen: 0.7,
        accuracy: 1,
        bpm: 1
    },
    upgrade = {
        name: "Jackpot",
        description: "Enemies are loaded. Really loaded.",
        coins: 2,
        speed: 1,
        damage: 1,
        hp: 1,
        regen: 1,
        accuracy: 0.9,
        bpm: 0.9
    },
    upgrade = {
        name: "Overclock",
        description: "Fire rate through the roof, accuracy takes a hit.",
        coins: 1,
        speed: 1,
        damage: 0.9,
        hp: 1,
        regen: 1,
        accuracy: 0.75,
        bpm: 1.6
    },
    upgrade = {
        name: "Dead Sprint",
        description: "Fast and fragile. Don't stop moving.",
        coins: 1,
        speed: 1.4,
        damage: 1,
        hp: 0.7,
        regen: 0.8,
        accuracy: 1,
        bpm: 1
    },
    upgrade = {
        name: "Vampire",
        description: "Regen so fast you barely notice getting hit.",
        coins: 1,
        speed: 0.9,
        damage: 0.9,
        hp: 1,
        regen: 2,
        accuracy: 1,
        bpm: 1
    },
    upgrade = {
        name: "Steady Hands",
        description: "Perfect accuracy, but take it slow.",
        coins: 1,
        speed: 0.9,
        damage: 1.1,
        hp: 1,
        regen: 1,
        accuracy: 1.6,
        bpm: 0.85
    },
    upgrade = {
        name: "War Economy",
        description: "Everything is slightly better. Nothing is free.",
        coins: 0.85,
        speed: 1.1,
        damage: 1.1,
        hp: 1.1,
        regen: 1.1,
        accuracy: 1.1,
        bpm: 1.1
    },
    upgrade = {
        name: "Bullet Storm",
        description: "So many bullets they can't breathe.",
        coins: 1,
        speed: 1,
        damage: 0.8,
        hp: 1,
        regen: 1,
        accuracy: 0.8,
        bpm: 1.8
    },
    upgrade = {
        name: "Paranoia",
        description: "Faster and more accurate, but fragile and broke.",
        coins: 0.8,
        speed: 1.2,
        damage: 1,
        hp: 0.8,
        regen: 1,
        accuracy: 1.2,
        bpm: 1
    },
    upgrade = {
        name: "Heavy Rounds",
        description: "Slow fire rate, massive damage per shot.",
        coins: 1,
        speed: 1,
        damage: 1.7,
        hp: 1,
        regen: 1,
        accuracy: 1.1,
        bpm: 0.6
    },
    upgrade = {
        name: "Combat Medic",
        description: "Stay healthy, stay deadly.",
        coins: 1,
        speed: 1,
        damage: 1.1,
        hp: 1.2,
        regen: 1.3,
        accuracy: 1,
        bpm: 1
    },
    upgrade = {
        name: "Lone Wolf",
        description: "No support, no problem. Pure survival instinct.",
        coins: 1.2,
        speed: 1.1,
        damage: 1.1,
        hp: 1.1,
        regen: 1.1,
        accuracy: 1,
        bpm: 1
    }
];